### PR TITLE
Speakers

### PR DESCRIPTION
**Pull request by Hoverbear**
@RustFestEU/zurich-2017 Please try this locally and cross reference with https://cfp.rustfest.eu/events/rustfest-ch/staff/program/sessions

We still need pictures for most.

### CODE REVIEW

**Comment by gandro** [comment]
Awesome, thanks! I didn't spot any errors. If we don't get the speaker pictures in time, we could either just disable them for now or alternatively add a default avatar.

I also modified descriptions a bit, such that the nice limericks we have render a bit better.

**Comment by flaki** [comment]
Added some fixes to CSS. Will have a look at speaker photos in a bit as well.

**Comment by flaki** [comment]
Thanks folks for the initial PR!

I have completely revamped the speakers section so we can have "speaker landing pages" which is required for the fancy Twitter cards and Facebook social.

I have tested the [cards](https://flaki.github.io/test/rustfest.html) previously on [the Card validator](https://cards-dev.twitter.com/validator), but unfortunately there is no other way to test those as to merge. Preliminary tests suggest this should be good.

I have initially included (set public) the already-announced speakers (3) and workshop (RustBridge), with the others landing in the next days, leading up to Monday last ticket batch.

Please review, and once merged I'll tweet these sessions out, with the next ones coming tomorrow!

Thankies!

**Review by Hoverbear — COMMENTED** [review]
LGTM (Can't approve my own PR)

**Pull request merged**
